name: Latest YouTube Videos

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCNFmyaoz7oKEvPeEtpJcnzw"
